#!/bin/bash
NAME='dev'
#création du conteneur
lxc init ubuntu:22.04 $NAMEsleep 2
#attachement du conteneur à la carte réseau
lxc network attach lxdbr0 $NAMEsleep 2
#demarrage du container
lxc start $NAMEsleep 2
#configuration du réseau
lxc exec $NAME -- sed -i 's|#DNS=|DNS=1.1.1.1|g' /etc/systemd/resolved.conf
lxc exec $NAME -- systemctl restart systemd-resolved
lxc exec $NAME -- bash -c 'echo -e "[Match]\nName=*\n\n[Network]\nDHCP=ipv4" > /etc/systemd/network/10-all.network'
lxc exec $NAME -- systemctl restart systemd-networkd
sleep 2
#installation des packageslxc exec $NAME apt update
lxc exec $NAME -- apt install apache2 -y
lxc exec $NAME -- apt install php -y
lxc exec $NAME -- apt install git -y
#suppresion de index.html
lxc exec $NAME rm /var/www/html/index.html
#récupération du répertoire git
lxc exec $NAME -- git clone 'https://github.com/jonathan-gu/jenkis_unit' /var/www/html/
sleep 2
#récupération de l'adresse ip du conteneur dev
CT_IP=$(lxc ls dev -f csv -c 4 | cut -d ' ' -f 1)
#récupation du résultat de la page
RESULT=$(curl $CT_IP/unit.php)sleep 2
#vérification si le contenu de la page renvoie "oui"
if [ "$RESULT" == "oui" ]
then        
#récupération du conteneur de prod        
lxc list -f csv -c n | grep -x prod
#vérificattion si un conteneur prod existe         
if [ $? -eq 0 ]
 then            
#arrêt du conteneur de prod            
lxc stop prod
sleep 2            
#suppresion du conteneur de prod            
lxc rm prod
sleep 2        
fi        
#arrêt du conteneur de dev        
lxc stop $NAME        sleep 2        
#renommage du contenur de dev en conteneur de prod        
lxc rename $NAME prod
sleep 2        
#démarrage du nouveau conteneur de prod        
lxc start prod
sleep 2else    
#arrêt du conteneur dev    lxc stop dev
sleep 2    
#suppression du conteneur de dev    
lxc rm dev
